apiVersion: apps/v1
kind: Deployment
metadata:
  name: hand-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hand-api
  template:
    metadata:
      labels:
        app: hand-api
    spec:
      containers:
      - name: hand-api
        image: hand-backend:latest
        envFrom:
        - secretRef:
            name: hand-env
        ports:
        - containerPort: 8080
